# .github/workflows/python-tests.yml
name: Python tests (unittest, 3.13)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'            # cache pip downloads based on requirements files

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests (discovery)
        run: |
          # Adjust -s/-p if your tests live somewhere else
          python -m unittest discover -s . -p "test*.py" -v
